import type { CoalPlant } from './types'

export const COAL_PLANTS: CoalPlant[] = [
  // Operating
  { id: 'scherer-ga', name: 'Plant Scherer', city: 'Juliette', state: 'GA', lat: 33.1075, lng: -83.7586, capacityMW: 3564, status: 'operating', owner: 'Georgia Power' },
  { id: 'gibson-in', name: 'Gibson Generating Station', city: 'Owensville', state: 'IN', lat: 38.3917, lng: -87.7342, capacityMW: 3340, status: 'operating', owner: 'AEP' },
  { id: 'rockport-in', name: 'Rockport Power Plant', city: 'Rockport', state: 'IN', lat: 37.8736, lng: -87.0503, capacityMW: 2600, status: 'operating', owner: 'AEP' },
  { id: 'bowen-ga', name: 'Plant Bowen', city: 'Cartersville', state: 'GA', lat: 34.2617, lng: -84.9997, capacityMW: 3499, status: 'operating', owner: 'Georgia Power' },
  { id: 'gavin-oh', name: 'Gavin Plant', city: 'Cheshire', state: 'OH', lat: 38.9042, lng: -82.1028, capacityMW: 2580, status: 'operating', owner: 'AEP' },
  { id: 'labadie-mo', name: 'Labadie Energy Center', city: 'Gray Summit', state: 'MO', lat: 38.4161, lng: -90.8722, capacityMW: 2311, status: 'operating', owner: 'Ameren' },
  { id: 'cardinal-oh', name: 'Cardinal Plant', city: 'Brilliant', state: 'OH', lat: 39.7192, lng: -80.9678, capacityMW: 1830, status: 'operating', owner: 'AEP' },
  { id: 'four-corners-nm', name: 'Four Corners Power Plant', city: 'Waterflow', state: 'NM', lat: 36.7014, lng: -108.4828, capacityMW: 1830, status: 'operating', owner: 'APS/AEP' },
  { id: 'laramie-wy', name: 'Laramie River Station', city: 'Wheatland', state: 'WY', lat: 42.0392, lng: -104.9272, capacityMW: 1785, status: 'operating', owner: 'WPSC' },
  { id: 'white-bluff-ar', name: 'White Bluff Steam Electric', city: 'Redfield', state: 'AR', lat: 34.4203, lng: -91.9239, capacityMW: 1668, status: 'retiring', retirementYear: 2028, owner: 'Entergy' },
  { id: 'independence-ar', name: 'Independence Steam Electric', city: 'Newark', state: 'AR', lat: 35.7031, lng: -91.4564, capacityMW: 1665, status: 'operating', owner: 'Entergy' },
  { id: 'limestone-tx', name: 'Limestone Electric', city: 'Jewett', state: 'TX', lat: 31.4131, lng: -96.4094, capacityMW: 1812, status: 'operating', owner: 'Vistra' },
  { id: 'colstrip-mt', name: 'Colstrip Steam Electric', city: 'Colstrip', state: 'MT', lat: 45.8924, lng: -106.6183, capacityMW: 2094, status: 'retiring', retirementYear: 2027, owner: 'Talen/PPL' },
  { id: 'intermountain-ut', name: 'Intermountain Power', city: 'Delta', state: 'UT', lat: 39.3156, lng: -112.5756, capacityMW: 1640, status: 'retiring', retirementYear: 2025, owner: 'IPA' },
  { id: 'sherco-mn', name: 'Sherco', city: 'Becker', state: 'MN', lat: 45.3769, lng: -93.9027, capacityMW: 2497, status: 'retiring', retirementYear: 2030, owner: 'Xcel Energy' },
  { id: 'ghent-ky', name: 'Ghent Power Plant', city: 'Ghent', state: 'KY', lat: 38.6839, lng: -84.9936, capacityMW: 2226, status: 'operating', owner: 'Kentucky Utilities' },
  { id: 'rush-island-mo', name: 'Rush Island Energy Center', city: 'Festus', state: 'MO', lat: 38.1756, lng: -90.3531, capacityMW: 1224, status: 'operating', owner: 'Ameren' },
  { id: 'fort-martin-wv', name: 'Fort Martin Power Station', city: 'Maidsville', state: 'WV', lat: 39.6564, lng: -80.0045, capacityMW: 1110, status: 'operating', owner: 'FirstEnergy' },
  { id: 'mountaineer-wv', name: 'Mountaineer Plant', city: 'New Haven', state: 'WV', lat: 39.3611, lng: -81.8033, capacityMW: 1300, status: 'operating', owner: 'AEP' },
  { id: 'john-amos-wv', name: 'John Amos Plant', city: 'St. Albans', state: 'WV', lat: 38.3775, lng: -81.8067, capacityMW: 2933, status: 'retiring', retirementYear: 2028, owner: 'AEP' },
  { id: 'hayden-co', name: 'Hayden Generating Station', city: 'Hayden', state: 'CO', lat: 40.4847, lng: -107.2642, capacityMW: 447, status: 'retiring', retirementYear: 2028, owner: 'Excel/PacifiCorp' },
  { id: 'comanche-co', name: 'Comanche Generating Station', city: 'Pueblo', state: 'CO', lat: 38.2789, lng: -104.4567, capacityMW: 1412, status: 'retiring', retirementYear: 2031, owner: 'Xcel Energy' },
  { id: 'weston-wi', name: 'Weston Power Plant', city: 'Rothschild', state: 'WI', lat: 44.8753, lng: -89.5633, capacityMW: 847, status: 'operating', owner: 'WPS' },
  { id: 'campbell-mi', name: 'J.H. Campbell', city: 'West Olive', state: 'MI', lat: 42.9781, lng: -86.2192, capacityMW: 1469, status: 'retiring', retirementYear: 2030, owner: 'Consumers Energy' },
  { id: 'merrimack-nh', name: 'Merrimack Station', city: 'Bow', state: 'NH', lat: 43.0497, lng: -71.5367, capacityMW: 470, status: 'operating', owner: 'Eversource' },
  { id: 'e-w-brown-ky', name: 'E.W. Brown Station', city: 'Harrodsburg', state: 'KY', lat: 37.7581, lng: -85.0014, capacityMW: 900, status: 'operating', owner: 'Kentucky Utilities' },
  { id: 'martin-lake-tx', name: 'Martin Lake Steam Electric', city: 'Tatum', state: 'TX', lat: 32.1578, lng: -94.5723, capacityMW: 2238, status: 'retiring', retirementYear: 2027, owner: 'Luminant/Vistra' },
  { id: 'san-miguel-tx', name: 'San Miguel Electric', city: 'Jourdanton', state: 'TX', lat: 28.8567, lng: -98.5028, capacityMW: 391, status: 'operating', owner: 'San Miguel' },
  { id: 'oak-creek-wi', name: 'Oak Creek Power Plant', city: 'South Milwaukee', state: 'WI', lat: 42.8733, lng: -87.8467, capacityMW: 1216, status: 'retiring', retirementYear: 2026, owner: 'We Energies' },
  // Retired
  { id: 'homer-city-pa', name: 'Homer City Generating Station', city: 'Homer City', state: 'PA', lat: 40.5478, lng: -79.1537, capacityMW: 1884, status: 'retired', retirementYear: 2023, owner: 'Homer City OL' },
  { id: 'bruce-mansfield-pa', name: 'Bruce Mansfield Plant', city: 'Shippingport', state: 'PA', lat: 40.6248, lng: -80.4468, capacityMW: 2490, status: 'retired', retirementYear: 2022, owner: 'FirstEnergy' },
  { id: 'pleasants-wv', name: 'Pleasants Power Station', city: 'Willow Island', state: 'WV', lat: 39.3064, lng: -81.4867, capacityMW: 1300, status: 'retired', retirementYear: 2019, owner: 'FirstEnergy' },
  { id: 'navajo-az', name: 'Navajo Generating Station', city: 'Page', state: 'AZ', lat: 36.8158, lng: -111.4297, capacityMW: 2250, status: 'retired', retirementYear: 2019, owner: 'SRP/Navajo Nation' },
  { id: 'brayton-point-ma', name: 'Brayton Point Station', city: 'Somerset', state: 'MA', lat: 41.7139, lng: -71.1497, capacityMW: 1535, status: 'retired', retirementYear: 2017, owner: 'NRG' },
  { id: 'big-brown-tx', name: 'Big Brown Steam Electric', city: 'Fairfield', state: 'TX', lat: 31.7178, lng: -96.0328, capacityMW: 1185, status: 'retired', retirementYear: 2018, owner: 'Luminant' },
  { id: 'monticello-tx', name: 'Monticello Steam Electric', city: 'Mount Pleasant', state: 'TX', lat: 33.5297, lng: -95.0503, capacityMW: 1800, status: 'retired', retirementYear: 2022, owner: 'Luminant' },
  { id: 'sioux-mo', name: 'Sioux Energy Center', city: 'Portage des Sioux', state: 'MO', lat: 38.9353, lng: -90.3553, capacityMW: 973, status: 'retired', retirementYear: 2022, owner: 'Ameren' },
  { id: 'tolk-tx', name: 'Tolk Station', city: 'Muleshoe', state: 'TX', lat: 34.1564, lng: -102.4453, capacityMW: 1067, status: 'retired', retirementYear: 2021, owner: 'Xcel Energy' },
  { id: 'columbia-wi', name: 'Columbia Energy Center', city: 'Portage', state: 'WI', lat: 43.5456, lng: -89.4289, capacityMW: 524, status: 'retired', retirementYear: 2024, owner: 'WPS/MG&E' },
  { id: 'edgewater-wi', name: 'Edgewater Generating Station', city: 'Sheboygan', state: 'WI', lat: 43.7258, lng: -87.7469, capacityMW: 380, status: 'retired', retirementYear: 2020, owner: 'We Energies' },
]
