import type { Utility } from './types'

export const UTILITIES: Utility[] = [
  {
    id: 'constellation',
    name: 'Constellation Energy',
    ticker: 'CEG',
    region: 'Mid-Atlantic / Midwest',
    states: ['PA', 'MD', 'IL', 'NY', 'NJ', 'OH'],
    type: 'IOU',
    nuclearStance: 'pro',
    stanceDetails: 'Largest US nuclear fleet operator (~10% of total US electricity from nuclear). Actively restarting Crane Clean Energy Center (TMI Unit 1) with DOE loan support. Deeply involved in SMR and advanced nuclear policy advocacy.',
    existingNuclear: ['Braidwood (IL)', 'Byron (IL)', 'Calvert Cliffs (MD)', 'Clinton (IL)', 'Dresden (IL)', 'Limerick (PA)', 'Peach Bottom (PA)', 'Quad Cities (IL)', 'Crane/TMI (PA — restarting)'],
    smrPlans: 'Signed LOIs with multiple advanced nuclear developers. Evaluating GE-Hitachi BWRX-300 and Oklo for site development. Crane restart is bellwether for SMR economics.',
    interconnectionStatus: 'PJM — established transmission customer, owns significant transmission assets. PJM queue reforms (Order 2023) have reduced backlog.',
    iso: 'PJM',
    priority: 1,
    okloRelevance: 'Highest priority — largest nuclear operator, pro-SMR, evaluating Oklo technology for future deployment.',
    recentNews: 'Announced Crane Clean Energy Center restart (3 Mile Island Unit 1) backed by $1.6B DOE loan guarantee. Microsoft signed 20-year PPA. Q4 2024: Acquired Calpine for $16.4B.',
    logoColor: '#1e40af'
  },
  {
    id: 'southern-company',
    name: 'Southern Company / Georgia Power',
    ticker: 'SO',
    region: 'Southeast',
    states: ['GA', 'AL', 'MS', 'TN'],
    type: 'IOU',
    nuclearStance: 'pro',
    stanceDetails: 'Built Vogtle Units 3&4 (AP1000) — first new US nuclear in 30+ years. Completed 2023-24. Signed PPA directly with Oklo for future SMR deployment. Strongest utility nuclear champion in the South.',
    existingNuclear: ['Vogtle 1-4 (GA)', 'Hatch 1-2 (GA)', 'Farley 1-2 (AL)'],
    smrPlans: 'SIGNED OKLO PPA. Evaluating additional SMR sites across GA/AL service territory to meet growing data center and industrial demand.',
    interconnectionStatus: 'SERC / Non-ISO — Southern Company operates its own vertically integrated transmission in a regulated monopoly structure. Interconnection directly with company.',
    iso: 'Non-ISO (SERC)',
    priority: 1,
    okloRelevance: 'Tier 1 — existing Oklo PPA signed. Direct customer relationship.',
    recentNews: '2024: Vogtle Unit 4 completed, full 4-unit fleet online. Georgia Power serving surging data center load in northern GA. Evaluating additional 3-5 GW of new generation.',
    logoColor: '#dc2626'
  },
  {
    id: 'vistra',
    name: 'Vistra Energy',
    ticker: 'VST',
    region: 'National',
    states: ['TX', 'IL', 'OH', 'PA', 'MI', 'CA', 'MD'],
    type: 'IOU',
    nuclearStance: 'pro',
    stanceDetails: 'Largest competitive power generator in the US after acquiring Energy Harbor (2024). Operates Comanche Peak (TX) + significant IL, OH, PA nuclear fleet. Strong nuclear life-extension commitments.',
    existingNuclear: ['Comanche Peak 1-2 (TX)', 'Clinton (IL)', 'Quad Cities share', 'Beaver Valley 1-2 (PA)', 'Davis-Besse (OH)', 'Perry (OH)', 'Palisades (MI — restart)'],
    smrPlans: 'Evaluating SMR deployment at legacy coal/nuclear sites. Palisades restart with Holtec underway (DOE loan approved). No specific Oklo contract announced.',
    interconnectionStatus: 'ERCOT (TX) / PJM (OH, PA, IL) / MISO — major competitive generator with established grid access.',
    iso: 'ERCOT / PJM / MISO',
    priority: 1,
    okloRelevance: 'Strong candidate — pro-nuclear, ERCOT exposure (TX market), significant brownfield nuclear sites for SMR co-location.',
    recentNews: '2024: Completed Energy Harbor acquisition for $3.43B. Stock up 200%+ on AI power demand. Committed to nuclear life extensions through 2050s.',
    logoColor: '#7c2d12'
  },
  {
    id: 'duke-energy',
    name: 'Duke Energy',
    ticker: 'DUK',
    region: 'Southeast / Midwest',
    states: ['NC', 'SC', 'FL', 'IN', 'OH', 'KY'],
    type: 'IOU',
    nuclearStance: 'pro',
    stanceDetails: 'Largest US electric utility by customers (~8M). Operates 11 nuclear units. Filed NRC license application for small modular reactor. Issued SMR RFP. Key Oklo addressable utility.',
    existingNuclear: ['McGuire 1-2 (NC)', 'Catawba 1-2 (NC/SC)', 'Oconee 1-3 (SC)', 'Harris (NC)', 'Robinson (SC)', 'Brunswick 1-2 (NC)'],
    smrPlans: 'Issued SMR technology RFP (2023). Evaluating NuScale, Holtec, GE-Hitachi BWRX-300. Exploring Oklo and others for smaller-scale deployment. IRP includes advanced nuclear as key option.',
    interconnectionStatus: 'PJM (IN/OH/Ky) / SERC (NC/SC/FL) — vertically integrated in regulated states, competitive in Indiana. Direct transmission ownership.',
    iso: 'PJM / SERC',
    priority: 1,
    okloRelevance: 'High priority — major IOU, nuclear-positive, large service territory with growing data center load (Charlotte, Triangle NC).',
    recentNews: '2024: Updated IRP includes 2.5 GW of advanced nuclear by 2035. North Carolina data center boom (Apple, Google, Meta facilities). Rate cases pending in multiple states.',
    logoColor: '#2563eb'
  },
  {
    id: 'tva',
    name: 'Tennessee Valley Authority',
    ticker: 'N/A (Federal)',
    region: 'Southeast',
    states: ['TN', 'AL', 'MS', 'KY', 'VA', 'NC', 'GA'],
    type: 'Federal',
    nuclearStance: 'pro',
    stanceDetails: 'Federal power authority — most active SMR deployer in the US. Selected GE-Hitachi BWRX-300 for Clinch River site (Oak Ridge, TN). Strong government backing, DOE partnership.',
    existingNuclear: ['Browns Ferry 1-3 (AL)', 'Sequoyah 1-2 (TN)', 'Watts Bar 1-2 (TN)'],
    smrPlans: 'BWRX-300 selected for Clinch River Nuclear Site adjacent to ORNL. Target first power: early 2030s. Potential to deploy multiple units.',
    interconnectionStatus: 'Non-ISO — TVA owns and operates its own 16,000-mile transmission grid across 7 states. No ISO/RTO interconnection queue; direct TVA process.',
    iso: 'Non-ISO (TVA)',
    priority: 1,
    okloRelevance: 'Moderate — already committed to BWRX-300, but Oak Ridge / DOE relationship relevant (Oklo has strong DOE/INL ties). Future units possible.',
    recentNews: '2024: DOE issued $9B in financing authority for advanced nuclear. TVA filed NRC Combined License Application for Clinch River BWRX-300. Partnering with ORNL on fuel cycle.',
    logoColor: '#16a34a'
  },
  {
    id: 'dominion-energy',
    name: 'Dominion Energy',
    ticker: 'D',
    region: 'Mid-Atlantic / Southeast',
    states: ['VA', 'NC', 'SC', 'WV', 'OH'],
    type: 'IOU',
    nuclearStance: 'exploring',
    stanceDetails: 'Operates Surry and North Anna nuclear plants. Has expressed SMR interest in IRP filings. Virginia\'s clean energy laws (VCEA) create nuclear tailwinds. No firm SMR contract signed.',
    existingNuclear: ['Surry 1-2 (VA)', 'North Anna 1-2 (VA)'],
    smrPlans: 'IRP mentions advanced nuclear as long-term option. Exploring SMR vendors but no RFP issued. Sold CT and SC assets to simplify.',
    interconnectionStatus: 'PJM — established transmission customer in VA/WV. Data center corridor (NoVA) is one of world\'s densest power markets.',
    iso: 'PJM',
    priority: 2,
    okloRelevance: 'Good candidate — Virginia is top US data center market, nuclear-friendly regulatory environment, existing nuclear operating history.',
    recentNews: '2024: Northern Virginia data center demand surging — PJM studying multiple new transmission projects. Dominion rate cases tied to data center growth.',
    logoColor: '#0ea5e9'
  },
  {
    id: 'ameren',
    name: 'Ameren',
    ticker: 'AEE',
    region: 'Midwest',
    states: ['MO', 'IL'],
    type: 'IOU',
    nuclearStance: 'pro',
    stanceDetails: 'Operates Callaway Nuclear Plant (MO). Missouri has no nuclear moratorium and supportive regulatory environment. Ameren exploring SMR as Callaway successor/supplement.',
    existingNuclear: ['Callaway (MO)'],
    smrPlans: 'Considering SMR deployment at or near Callaway site post-2040. Missouri legislature supportive of nuclear investment recovery mechanisms.',
    interconnectionStatus: 'MISO — established transmission customer. Callaway has existing 1,200+ MW grid connection.',
    iso: 'MISO',
    priority: 2,
    okloRelevance: 'Good fit — Missouri nuclear-friendly, Callaway site infrastructure, utility open to nuclear expansion.',
    recentNews: '2024: Missouri data center growth accelerating (Kansas City tech hub). Ameren IRP update includes advanced nuclear evaluation.',
    logoColor: '#b45309'
  },
  {
    id: 'nextera',
    name: 'NextEra Energy',
    ticker: 'NEE',
    region: 'Southeast / National',
    states: ['FL', 'IA', 'WI', 'ME', 'NH'],
    type: 'IOU',
    nuclearStance: 'neutral',
    stanceDetails: 'Largest US utility by market cap. Focus on wind/solar. Operates nuclear but has not committed to new nuclear. Sold Point Beach to Holtec. Cautious on SMR economics.',
    existingNuclear: ['Turkey Point 3-4 (FL)', 'St. Lucie 1-2 (FL)', 'Seabrook (NH)', 'Duane Arnold (IA — retired)'],
    smrPlans: 'No announced SMR plans. IRP focused on solar/storage/wind at massive scale. Views SMR as too expensive vs. renewables currently.',
    interconnectionStatus: 'SERC (FL) / ISO-NE (NH) / MISO (IA) — major transmission customer across multiple ISOs.',
    iso: 'SERC / ISO-NE / MISO',
    priority: 3,
    okloRelevance: 'Lower priority — not actively pursuing SMR. However FL nuclear operations and massive capital base means potential if SMR economics improve.',
    recentNews: '2024: Strong renewables growth. Florida data center and AI demand creating new load. Monitoring nuclear policy developments.',
    logoColor: '#ea580c'
  },
  {
    id: 'exelon',
    name: 'Exelon (ComEd / BGE / PECO / etc.)',
    ticker: 'EXC',
    region: 'Mid-Atlantic / Midwest',
    states: ['IL', 'MD', 'DC', 'PA', 'NJ', 'DE'],
    type: 'IOU',
    nuclearStance: 'pro',
    stanceDetails: 'Regulated utility holding company (distribution only post-Constellation spin-off). ComEd (IL) supports nuclear through Zero Emission Credits (ZEC) program. Advocates for nuclear-friendly policy.',
    existingNuclear: ['Distribution only — generation through Constellation (parent company)'],
    smrPlans: 'Distribution utilities. SMR generation would flow through Constellation or third-party PPAs.',
    interconnectionStatus: 'PJM — major distribution customer. Chicago area (ComEd) is major load center.',
    iso: 'PJM',
    priority: 2,
    okloRelevance: 'Indirect — Exelon utilities could be PPA offtakers for Oklo power. Illinois nuclear-favorable regulation.',
    recentNews: '2024: Illinois data center growth (Chicago second largest US data center market). ComEd upgrading grid for AI workloads.',
    logoColor: '#7c3aed'
  },
  {
    id: 'pacificorp',
    name: 'PacifiCorp / Rocky Mountain Power',
    ticker: 'BRK subsidiary',
    region: 'West',
    states: ['UT', 'OR', 'WY', 'WA', 'CA', 'ID'],
    type: 'IOU',
    nuclearStance: 'neutral',
    stanceDetails: 'Berkshire Hathaway Energy subsidiary. No nuclear. Serves Wyoming (key Oklo site state) and Utah. Rocky Mountain Power IRP evaluating diverse clean energy mix.',
    existingNuclear: [],
    smrPlans: 'No announced SMR plans. Evaluating long-duration storage, wind, geothermal. Wyoming/Utah states are nuclear-friendly — potential future interest.',
    interconnectionStatus: 'WECC (non-ISO) — owns significant transmission in Mountain West. Key transmission corridor for Oklo Wyoming/Utah sites.',
    iso: 'Non-ISO (WECC)',
    priority: 2,
    okloRelevance: 'Key distribution/transmission partner for Wyoming/Utah Oklo sites. Could be future SMR offtaker.',
    recentNews: '2024: Wildfire liability concerns. Utah and Wyoming data center growth (Phoenix boom + tech migration). Rocky Mountain Power IRP under state commission review.',
    logoColor: '#9333ea'
  },
  {
    id: 'puget-sound-energy',
    name: 'Puget Sound Energy',
    ticker: 'Private (Macquarie)',
    region: 'Northwest',
    states: ['WA'],
    type: 'IOU',
    nuclearStance: 'exploring',
    stanceDetails: 'Washington state utility exploring advanced nuclear. Washington has active data center growth (Microsoft, Amazon HQ) driving demand. WA legislature has been reviewing nuclear energy bills.',
    existingNuclear: [],
    smrPlans: 'Monitoring SMR developments. Washington has no nuclear moratorium (unlike OR). Evaluating options post-2030.',
    interconnectionStatus: 'WECC (non-ISO) — Pacific Northwest transmission. Major load center (Seattle metro).',
    iso: 'Non-ISO (WECC)',
    priority: 2,
    okloRelevance: 'Interesting fit — WA is major tech hub, PSE is key utility, and state may move toward advanced nuclear.',
    recentNews: '2024: Microsoft / Amazon AI build-out driving Washington power demand surge. Grid reliability concerns from hydropower variability. Nuclear energy bills introduced in Olympia.',
    logoColor: '#0369a1'
  },
  {
    id: 'xcel-energy',
    name: 'Xcel Energy',
    ticker: 'XEL',
    region: 'Midwest / Southwest',
    states: ['MN', 'CO', 'TX', 'WI', 'ND', 'SD', 'NM'],
    type: 'IOU',
    nuclearStance: 'neutral',
    stanceDetails: 'Operates Monticello and Prairie Island (MN) — both life-extended. MN has nuclear moratorium on new large plants (but SMRs may differ). Palo Verde share (AZ). Cautious on new nuclear.',
    existingNuclear: ['Monticello (MN — extended)', 'Prairie Island 1-2 (MN — extended)', 'Palo Verde share (AZ)'],
    smrPlans: 'Evaluating options for 2030+ in Colorado. CO has no nuclear moratorium. No vendor contracts.',
    interconnectionStatus: 'MISO (MN/ND/SD/WI) / SPP (CO/TX/NM) — established transmission customer in both ISOs.',
    iso: 'MISO / SPP',
    priority: 3,
    okloRelevance: 'Moderate — Colorado service territory is nuclear-friendly. Xcel has nuclear operating experience.',
    recentNews: '2024: Colorado energy transition plan filed. Minnesota nuclear life extension secured through 2030+.',
    logoColor: '#0284c7'
  },
  {
    id: 'entergy',
    name: 'Entergy Corporation',
    ticker: 'ETR',
    region: 'South',
    states: ['AR', 'LA', 'MS', 'TX'],
    type: 'IOU',
    nuclearStance: 'neutral',
    stanceDetails: 'Sold merchant nuclear fleet. Retains utility nuclear in Southern states. No announced new nuclear. MISO/ERCOT exposure.',
    existingNuclear: ['Arkansas Nuclear One 1-2 (AR)', 'Grand Gulf (MS)', 'River Bend (LA)', 'Waterford 3 (LA)'],
    smrPlans: 'No announced SMR plans. Focus on regulated utility operations.',
    interconnectionStatus: 'MISO (AR/LA/MS) / ERCOT (TX) — established transmission customers.',
    iso: 'MISO / ERCOT',
    priority: 3,
    okloRelevance: 'Potential — existing nuclear operating history, Louisiana/Arkansas nuclear-friendly. Growing data center interest.',
    recentNews: '2024: Louisiana industrial load growth (LNG, manufacturing). Data center inquiries increasing. IRP review ongoing.',
    logoColor: '#be185d'
  },
  {
    id: 'nv-energy',
    name: 'NV Energy',
    ticker: 'BRK subsidiary',
    region: 'West',
    states: ['NV'],
    type: 'IOU',
    nuclearStance: 'neutral',
    stanceDetails: 'Nevada has no nuclear moratorium. NV Energy serves Las Vegas (data center hub) and northern NV (Tahoe Reno Industrial Center — Switch campus). No nuclear currently.',
    existingNuclear: [],
    smrPlans: 'No announced SMR plans. IRP focused on solar/storage. However Nevada is extremely relevant for Oklo data center strategy (Switch RFP).',
    interconnectionStatus: 'WECC (non-ISO) — NV Energy owns transmission serving Nevada. Key interconnection for Switch/TRIC campus in Reno area.',
    iso: 'Non-ISO (WECC)',
    priority: 2,
    okloRelevance: 'Key utility for Switch/Reno site and Las Vegas data center corridor. Future SMR offtaker potential.',
    recentNews: '2024: Nevada data center boom — Las Vegas and TRIC campuses expanding rapidly. AI compute demand exceeding grid capacity projections.',
    logoColor: '#ca8a04'
  },
  {
    id: 'firstenergy',
    name: 'FirstEnergy',
    ticker: 'FE',
    region: 'Mid-Atlantic / Midwest',
    states: ['OH', 'PA', 'WV', 'NJ', 'MD'],
    type: 'IOU',
    nuclearStance: 'exploring',
    stanceDetails: 'Distribution utility. Sold nuclear generation (now Vistra/Energy Harbor). Key distribution utility in Ohio and Pennsylvania — both nuclear-friendly states. Monitoring SMR developments.',
    existingNuclear: ['None (divested to Energy Harbor, now Vistra)'],
    smrPlans: 'Exploring options for long-term clean power. OH, PA are nuclear-friendly regulatory environments.',
    interconnectionStatus: 'PJM — major distribution customer in Ohio and Pennsylvania service territories.',
    iso: 'PJM',
    priority: 3,
    okloRelevance: 'Key distribution utility for Ohio and PA Oklo sites (Fort Cherry, Cadiz tarea). Could be a power offtaker.',
    recentNews: '2024: Ohio data center growth, Columbus tech hub. Pennsylvania nuclear-positive political environment.',
    logoColor: '#b91c1c'
  },
  {
    id: 'liberty-utilities',
    name: 'Liberty Utilities / Algonquin Power',
    ticker: 'AQN',
    region: 'Mid-Atlantic',
    states: ['PA', 'NJ', 'NY', 'OH',
    type: 'IOU',
    nuclearStance: 'exploring',
    stanceDetails: 'Owner of multiple Oklo candidate sites (Fort Cherry, PA; Redhawk, PA). Direct relationship with Oklo as site developer/partner. Mid-size regulated utility.',
    existingNuclear: [],
    smrPlans: 'Site developer for Oklo candidate locations. Evaluating nuclear energy as part of clean energy portfolio transition.',
    interconnectionStatus: 'PJM — established distribution utility in Pennsylvania and New Jersey.',
    iso: 'PJM',
    priority: 1,
    okloRelevance: 'DIRECT SITE PARTNER — owns Fort Cherry and Redhawk sites being evaluated for Oklo deployment. Highest relationship priority.',
    recentNews: '2024: Algonquin Power rebranding and strategic review. Liberty Utilities continues as regulated distribution arm.',
    logoColor: '#059669'
  },
]
